In [3]:
import pandas as pd
from pandas import read_csv
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [7]:
dataframe=pd.read_csv('D:\\Assignment Excelr\\KNN\\glass.csv')

In [8]:
dataframe

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [9]:
dataframe.dtypes

RI      float64
Na      float64
Mg      float64
Al      float64
Si      float64
K       float64
Ca      float64
Ba      float64
Fe      float64
Type      int64
dtype: object

In [10]:
dataframe.shape

(214, 10)

In [11]:
array = dataframe.values
X=array[:,0:9]
Y=array[:,9]

In [12]:
scale=StandardScaler()
scaled_data=scale.fit_transform(X)

In [13]:
scaled_data

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [14]:
X=scaled_data

In [15]:
X

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [16]:
num_folds = 10
kfold = KFold(n_splits=10)

In [23]:
model=KNeighborsClassifier(n_neighbors=2)
results=cross_val_score(model,X,Y,cv=kfold)

In [24]:
print(results.mean())

0.5844155844155845


In [2]:
import numpy
from sklearn.model_selection import GridSearchCV

In [26]:
n_neighbors = numpy.array(range(1,41))
param_grid= dict(n_neighbors=n_neighbors)
param_grid

{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40])}

In [27]:
model=KNeighborsClassifier()
grid=GridSearchCV(estimator=model,param_grid=param_grid)
grid.fit(X,Y)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])})

In [28]:
print(grid.best_score_)
print(grid.best_params_)

0.6729789590254706
{'n_neighbors': 2}


In [29]:
#ZOO dataset

In [4]:
data=pd.read_csv('D:\\Assignment Excelr\\KNN\\Zoo.csv')
data

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  type  
0          1     1  
1          1     1  
2          0     4  
3          1     1  
4          1     1  
..       ...   ...  
96         1     1  
97         0     6  
98         1     1  
99         0     7  
100        0     2  

[101 rows x 18 columns]

In [5]:
data=data.drop('animal name',axis=1)

In [6]:
#GRID

In [10]:
n_neighbors = numpy.array(range(1,41))
param_grid= dict(n_neighbors=n_neighbors)
param_grid

{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40])}

In [12]:
model=KNeighborsClassifier()
grid=GridSearchCV(estimator=model,param_grid=param_grid)
grid.fit(X,Y)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])})

In [13]:
print(grid.best_score_)
print(grid.best_params_)

0.9304761904761903
{'n_neighbors': 1}


In [14]:
data.dtypes

hair        int64
feathers    int64
eggs        int64
milk        int64
airborne    int64
aquatic     int64
predator    int64
toothed     int64
backbone    int64
breathes    int64
venomous    int64
fins        int64
legs        int64
tail        int64
domestic    int64
catsize     int64
type        int64
dtype: object

In [15]:
data.shape

(101, 17)

In [16]:
array = data.values
X=array[:,1:8]
Y=array[:,1:8]

In [17]:
scale=StandardScaler()
scaled_data1=scale.fit_transform(X)

In [18]:
scaled_data1

array([[-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
         0.89642146,  0.80977633],
       [-0.49690399, -1.1852

In [19]:
X=scaled_data1

In [20]:
X

array([[-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
         0.89642146,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399, -1.18522652,  1.20971676, -0.55829053, -0.74420841,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
        -1.1155467 ,  0.80977633],
       [-0.49690399,  0.84372057, -0.82663978, -0.55829053,  1.34370962,
         0.89642146,  0.80977633],
       [-0.49690399, -1.1852

In [21]:
num_folds = 10
kfold = KFold(n_splits=10)

In [22]:
model=KNeighborsClassifier(n_neighbors=2)
results=cross_val_score(model,X,Y,cv=kfold)

In [23]:
print(results.mean())

0.8699999999999999
